name: "Post Slack"
description: "Post Message to Slack"
author: "Jungyoul Yu <@nalbam>"

branding:
  icon: "message-square"
  color: "purple"

runs:
  using: docker
  image: docker://opspresso/action-slack:v0.2.1
